language: rust
cache: cargo

rust:
  - nightly

os:
  - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y pkg-config

sudo: true

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cargo install kcov
        cargo kcov
      fi